blank_issues_enabled: false
contact_links:
  - name: Propose an idea
    url: https://github.com/mfukushim/avatar-shell/discussions/categories/ideas
    about: Discuss any ideas and feature requests
  - name: Ask a question
    url: https://github.com/mfukushim/avatar-shell/discussions/categories/q-a
    about: Please ask any Q&A here
