name: Check
on:
  workflow_dispatch: null
  pull_request:
    branches:
      - dev_release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  call-entry-ci:
    uses: ./.github/workflows/ci.yml
    with:
      distribution-channel: 'test'
