name: pre-build
on:
  workflow_dispatch: null
  push:
    branches:
      - dev_release
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  run-ci:
    name: ci.yml
    uses: ./.github/workflows/ci.yml
    with:
      distribution-channel: 'alpha'
    permissions:
      contents: write
      id-token: write
      attestations: write
#  call-compile-test:
#    uses: ./.github/workflows/compile-and-test.yml
#    with:
#      distribution-channel: 'test'
#      app-version: '0.0.1'
